name: hitl_system
channels:
  - anaconda
  - pytorch
  - dglteam
  - conda-forge/label/cf202003
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.7.3
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - boto=2.49.0
  - boto3=1.17.12
  - botocore=1.20.12
  - brotlipy=0.7.0
  - ca-certificates=2019.11.28
  - cachetools=4.2.1
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=3.0.4
  - cryptography=3.3.1
  - cudatoolkit=10.1.243
  - cycler=0.10.0
  - cython=0.29.21
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - dgl-cuda10.1=0.5.3
  - entrypoints=0.3
  - expat=2.2.10
  - faiss-cpu=1.7.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - gensim=3.8.0
  - glib=2.67.4
  - google-api-core=1.25.1
  - google-auth=1.27.0
  - google-cloud-core=1.6.0
  - google-cloud-storage=1.36.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.2.0
  - googleapis-common-protos=1.52.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.20.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.17.0
  - jinja2=2.11.3
  - jmespath=0.10.0
  - joblib=1.0.0
  - jpeg=9b
  - json5=0.9.5
  - jsonpickle=1.4.1
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.1
  - jupyterlab=2.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - jupyterlab_widgets=1.0.0
  - kaleido-core=0.2.1
  - kiwisolver=1.3.1
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libcrc32c=1.1.1
  - libedit=3.1.20191231
  - libfaiss=1.7.0
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.3.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - mathjax=2.7.7
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.1
  - mkl_random=1.1.1
  - msgpack-numpy=0.4.7
  - msgpack-python=1.0.2
  - multidict=4.7.6
  - nbclient=0.5.2
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.5
  - ninja=1.10.2
  - nodejs=12.4.0
  - notebook=6.2.0
  - nspr=4.29
  - nss=3.62
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1j
  - packaging=20.9
  - pandas=1.2.1
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.8.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=21.0.1
  - plotly=4.14.3
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - protobuf=3.14.0
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pygments=2.8.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - python-kaleido=0.2.1
  - python_abi=3.7
  - pytorch=1.7.1
  - pytz=2021.1
  - pyvis=0.1.8.2
  - pyyaml=5.4.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=5.0.2
  - qtpy=1.9.0
  - readline=8.1
  - redis=5.0.3
  - redis-py=3.5.3
  - requests=2.25.1
  - retrying=1.3.3
  - rsa=4.7.1
  - s3transfer=0.3.4
  - scikit-learn=0.23.2
  - scipy=1.6.0
  - seaborn=0.11.1
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.15.0
  - smart_open=4.2.0
  - sqlalchemy=1.3.5
  - sqlite=3.34.0
  - terminado=0.9.2
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.56.0
  - traitlets=5.0.5
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.5.1
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - dill==0.3.3
    - pandarallel==1.5.2

