DATA_LOC: './../generated_data_v1/us_import'
us_import1:
  'ape':
    - 'emb_dim' : 12
      'file': 'model_12_1612559773'
    - 'emb_dim' : 16
      'file': 'model_16_1612559780'
  'mead':
    - 'emb_dim' : 16
      'file': 'model_16_1612559651'
    - 'emb_dim' : 12
      'file': 'model_12_1612559784'
    - 'emb_dim' : 20
      'file' : 'model_20_1612580597'
    - 'emb_dim' : 24
      'file' : 'model_24_1612581257'  
    
us_import2:
  'ape': 
    - 'emb_dim' : 12
      'file': 'model_12_1612585191'
    - 'emb_dim' : 16
      'file': 'model_16_1612585970'
    - 'emb_dim' : 20
      'file' : 'model_20_1612586753'
    - 'emb_dim' : 24
      'file' : 'model_24_1612587468'  
  'mead': 
    - 'emb_dim' : 16
      'file': 'model_16_1612583200'
    - 'emb_dim' : 12
      'file': 'model_12_1612582373'
    - 'emb_dim' : 20
      'file' : 'model_20_1612584008'
    - 'emb_dim' : 24
      'file' : 'model_24_1612581599'  
      
  
us_import3:
  'ape': 
    - 'emb_dim' : 12
      'file': 'model_12_1612588188'
    - 'emb_dim' : 16
      'file': 'model_16_1612588849'
    - 'emb_dim' : 20
      'file' : 'model_20_1612589512'
    - 'emb_dim' : 24
      'file' : 'model_24_1612590216'  
  'mead':  
    - 'emb_dim' : 12
      'file': 'model_12_1612582586'
    - 'emb_dim' : 16
      'file': 'model_16_1612583379'
    - 'emb_dim' : 20
      'file' : 'model_20_1612584170'
    - 'emb_dim' : 24
      'file' : 'model_24_1612584965'  
      
            
us_import4:
  'ape': 
    - 'emb_dim' : 12
      'file': 'model_12_1612590985'
    - 'emb_dim' : 16
      'file': 'model_16_1612591739'
    - 'emb_dim' : 20
      'file' : 'model_20_1612592484'
    - 'emb_dim' : 24
      'file' : 'model_24_1612593260'       
  'mead': 
    - 'emb_dim' : 12
      'file': 'model_12_1612582741'
    - 'emb_dim' : 16
      'file': 'model_16_1612583535'
    - 'emb_dim' : 20
      'file' : 'model_20_1612584330'
    - 'emb_dim' : 24
      'file' : 'model_24_1612585127'  
      
us_import5:
  'ape': 
    - 'emb_dim' : 12
      'file': 'model_12_1612594009'
    - 'emb_dim' : 16
      'file': 'model_16_1612594749'
    - 'emb_dim' : 20
      'file' : 'model_20_1612595443'
    - 'emb_dim' : 24
      'file' : 'model_24_1612596202'  
  'mead': 
    - 'emb_dim' : 12
      'file': 'model_12_1612582894'
    - 'emb_dim' : 16
      'file': 'model_16_1612583693'
    - 'emb_dim' : 20
      'file' : 'model_20_1612584487'
    - 'emb_dim' : 24
      'file' : 'model_24_1612585292'  
  
      
            
      