SRC_DATA_LOC : './../Data_Raw/us_import'
processedData_DIR : 'generated_data_v1'
subdir: us_import
train_period: 6
test_period: 1
epoch_fileList : 'epoch_fileList.json'
'use_cols':
    - PanjivaRecordID
    - ConsigneePanjivaID
    - ShipperPanjivaID
    - Carrier
    - ShipmentOrigin
    - ShipmentDestination
    - PortOfUnlading
    - PortOfLading
    - HSCode
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'low_freq_bound': 5