'file_path' : './../Data_Raw/us_import'
normalize:
    - 'primary_key': 'ConsigneePanjivaID'
      'primary_key_type': 'int'
      'columns':
        - 'ConsigneeName'
        - 'ConsigneeFullAddress' 
        - 'ConsigneeRoute' 
        - 'ConsigneeCity' 
        - 'ConsigneeStateRegion' 
        - 'ConsigneePostalCode' 
        - 'ConsigneeCountry' 
        - 'ConsigneeURL' 
        - 'ConsigneeLocalDUNS' 
        - 'ConsigneePanjivaID' 
        - 'ConsigneeStockTickers' 
        - 'ConsigneeCleanedStockTickers' 
        - 'ConsigneeUltimateParentStockTickers' 
        - 'ConsigneeUltimateParentCleanedStockTickers' 
        - 'ConsigneeUltimateParentName' 
        - 'ConsigneeOriginalFormat'
    - 'primary_key': 'ShipperPanjivaID'
      'primary_key_type': 'int'
      'columns': 
        - 'ShipperName'  
        - 'ShipperFullAddress'  
        - 'ShipperRoute'  
        - 'ShipperCity'  
        - 'ShipperStateRegion'  
        - 'ShipperPostalCode'  
        - 'ShipperCountry'  
        - 'ShipperURL'  
        - 'ShipperLocalDUNS'  
        - 'ShipperPanjivaID'  
        - 'ShipperStockTickers'  
        - 'ShipperCleanedStockTickers'  
        - 'ShipperUltimateParentStockTickers'  
        - 'ShipperUltimateParentCleanedStockTickers'  
        - 'ShipperUltimateParentName'  
        - 'ShipperOriginalFormat'
    - 'primary_key': 'PortOfUnlading'
      'columns': 
        - 'PortOfUnlading'  
        - 'PortOfUnladingRegion'  
      'primary_key_type': 'str'
    - 'primary_key': 'PortOfLading'
      'columns': 
        - 'PortOfLading'
        - 'PortOfLadingRegion'
        - 'PortOfLadingCountry'
      'primary_key_type': 'str' 
    - 'primary_key': 'ShipmentDestination'
      'columns': 
        - 'ShipmentDestination'
        - 'ShipmentDestinationRegion'
      'primary_key_type': 'str' 
record_id : 
    name : 'PanjivaRecordID'
    type : 'int'
